# Generated by Django 4.2.25 on 2025-10-11 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailySoul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='affirmation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='affirmations/'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='category',
            field=models.CharField(choices=[('self-love', 'Self Love'), ('motivation', 'Motivation'), ('calm', 'Calm'), ('gratitude', 'Gratitude'), ('healing', 'Healing')], default='self-love', max_length=50),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
